version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  install-build-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run: node --version
      - setup_remote_docker
      - run: npm install
      - run: npm run test

workflows:
  build-and-test:
    jobs:
      - install-build-test
