version: 2.1
orbs:
  node: circleci/node:12.16.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - setup_remote_docker
            - run: npm install
            - run: npm run build && npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
