version: 2.1
jobs:
  install-node-example:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version

  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      - run: npm run test

workflows:
  build-and-test:
    jobs:
      - install-node-example
      - build-and-test
