version: 2.1
jobs:
  install-build-test:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - setup_remote_docker
      - run: node --version
      - run: npm install
      - run: npm run test

workflows:
  build-and-test:
    jobs:
      - install-build-test
