version: 2.1

install_pnpm: &install_pnpm
  # Control pnpm version dependency explicitly
  run:
    name: install pnpm
    command: sudo npm i -g pnpm@4.11.6

jobs:
  install-build-test:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - setup_remote_docker
      - <<: *install_pnpm
      - run: pnpm install --frozen-lockfile
      - run: npm run test

workflows:
  build-and-test:
    jobs:
      - install-build-test
